services:
  postgres:
    build:
      context: ./postgres
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: northwind
    ports:
      - "5432:5432"
    volumes:
      - .postgres_data:/var/lib/postgresql/data

  sqlite:
    build:
      context: ./sqlite
    container_name: sqlite_db

  # Funfacts:
  # MSSQL does not have arm64 arch (only amd64)
  # Known issue for Docker for Mac is that mounting volumes does not work
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_db
    restart: always
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  postgres_data:
  mssql_data:
