services:
  postgres:
    image: postgres:16 # at least postgres is available for arm64 arch out of the box
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  sqlite:
    image: keinos/sqlite3:latest # since this one has arm64 arch
    container_name: sqlite_db
    command: tail -f /dev/null # Keeps the container running
    volumes:
      - sqlite_data:/data

  # Funfacts:
  # MSSQL does not have arm64 arch (only amd64)
  # Known issue for Docker for Mac is that mounting volumes does not work
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_db
    restart: always
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  postgres_data:
  sqlite_data:
  mssql_data:
