version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: mongo_north0
    ports:
      - "27017:27017"
    volumes:
      - ./dump:/dump
      - ./init:/docker-entrypoint-initdb.d
