DROP TABLE IF EXISTS "Employees";
DROP TABLE IF EXISTS "Customers";
DROP TABLE IF EXISTS "Categories";
DROP TABLE IF EXISTS "Products";
DROP TABLE IF EXISTS "Suppliers";
DROP TABLE IF EXISTS "Orders";
DROP TABLE IF EXISTS "Order Details";
DROP TABLE IF EXISTS "Shippers";